version: '3.9'

services:
  web_go_server:
    container_name: web_go_server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    entrypoint: sleep infinity
    ports:
      - "55002:55000"
      - "8189:8080"
    volumes:
      - .:/app